# Generated by Django 4.1.5 on 2024-02-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_newslettersubscribsion'),
    ]

    operations = [
        migrations.CreateModel(
            name='travel_cnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
