# Generated by Django 4.1.5 on 2024-02-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student name')),
                ('email', models.EmailField(max_length=200, verbose_name='Student Email')),
            ],
        ),
    ]
