# Generated by Django 4.1.5 on 2024-02-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_students',
            old_name='number',
            new_name='phone',
        ),
    ]
